Web-Cab-Sharing/cabsharing/accounts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='user_login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html') , name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',email_template_name='accounts/password_reset_email.html',subject_template_name='accounts/password_reset_subject.txt'),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    # normal urls are not working in my case

    re_path(r'^(?P<pk>\d+)/detail/$', views.UserDetailView.as_view(), name='user_detail'),
    # re_path(r'^(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(template_name='accounts/user_delete.html'), name='user_delete'),

    re_path(r'^(?P<pk>\d+)/update/$', views.UserUpdateView.as_view(template_name='accounts/haha.html'), name='user_update'),


    ]

Web-Cab-Sharing/cabsharing/bookings/urls.py
from django.urls import path, re_path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('create/', views.create_booking, name='bookings_create'),
    path('', views.IndexView.as_view(), name='index'),
    path('mybookings/', views.my_bookings, name='my_bookings'),
    #path('<pk>/', views.DetailView.as_view(), name='detail'),
    re_path(r'^(?P<pk>\d+)/update/$', views.BookingUpdateView.as_view(template_name='bookings/bookings_update.html'), name='bookings_update'),
    re_path(r'^(?P<pk>\d+)/delete/$', views.BookingDeleteView.as_view(template_name='bookings/bookings_delete.html'), name='bookings_delete'),
    re_path(r'^(?P<pk>\d+)/join/$', views.join_group , name='group_join'),
    re_path(r'^(?P<pk>\d+)/leave/$', views.leave_group , name='group_leave'),
    re_path(r'^(?P<pk>\d+)/info/$', views.grp_info, name='group_info'),

]

Web-Cab-Sharing/cabsharing/cabsharing/urls.py
from django.contrib import admin
from django.urls import path, include
#from register.views import homepage
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', auth_views.LoginView.as_view(template_name='register/homepage.html'), name='user_login'),
    path('bookings/', include('bookings.urls')),
    #path('password_reset', auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html', name = 'password_reset')),
]







#path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='user_login'),

Web-Cab-Sharing/cabsharing/register/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'register'


urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.filter, name='user_dashboard'),
    path('logout/', auth_views.LogoutView.as_view(), name='user_logout'),
]

Web-Cab-Sharing/cabsharing/register/models.py
from django.db import models

Web-Cab-Sharing/cabsharing/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

Web-Cab-Sharing/cabsharing/register/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.views import generic
from .forms import SignUpForm
from bookings.forms import FilterForm
from bookings.models import Bookings
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.views.generic import CreateView , ListView, UpdateView , DeleteView, DetailView
from braces.views import LoginRequiredMixin


def index(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
            return redirect('register:user_dashboard')
    else:
        form = SignUpForm()
    return render(request, 'register/index.html', {'form': form})


def homepage(request):
    if request.method == 'POST':
        #form = SignUpForm(request.POST)
        #if form.is_valid():
         #   form.save()
            #username = form.cleaned_data.get('username')
            #raw_password = form.cleaned_data.get('password1')
            user = authenticate(request.POST)
            if user is not None:
                login(request, user)
                return redirect('register:user_dashboard')
   #     form = SignUpForm()
    return render(request, 'register/homepage.html', {})


#@login_required()
#def user_dashboard(request):
#    return render(request, 'register/dashboard.html',)

#class UserDetailView(LoginRequiredMixin, ListView):
    #model = User
    #template_name='register/dashboard.html'


def filter(request):
    if request.method=='POST':
        form=FilterForm(request.POST)
        if form.is_valid():

            custom=Bookings.objects.filter(date__gte=datetime.date.today())
            hehehe=[]
            if(not (form.cleaned_data['start_position']=='')):
                custom=custom.filter(start_position__contains=form.cleaned_data['start_position'])
                hehehe.append("From:"+form.cleaned_data['start_position'])
            if(not (form.cleaned_data['destination']=='')):
                custom=custom.filter(destination__contains=form.cleaned_data['destination'])
                hehehe.append("To:"+form.cleaned_data['destination'])
            if((form.cleaned_data['date'])):
                custom=custom.filter(date__iexact=form.cleaned_data['date'])

                hehehe.append("Date:"+form.cleaned_data['date'].strftime('%d-%m-%y'))
            if(form.cleaned_data['time']):
                time1=datetime.datetime.strptime(str(form.cleaned_data['time']), '%H:%M:%S')-datetime.timedelta(hours=1)
                time2=datetime.datetime.strptime(str(form.cleaned_data['time']), '%H:%M:%S')+datetime.timedelta(hours=1)
                custom=custom.filter(time__gte=time1)
                custom=custom.filter(time__lte=time2)
                hehehe.append("Time:"+form.cleaned_data['time'].strftime('%H:%M'))
            #custom=custom.filter(gender__iexact=form.cleaned_data['gender'])
            #hehehe.append("Gender:"+str(form.cleaned_data['gender']))
            context={}
            context['custom']=custom
            context['hehehe']=hehehe
            new_form=FilterForm()
            context['form'] = new_form
            return render(request, 'register/dashboard.html', context)
    else:
        new_form= FilterForm()
        context={}
        context['form']=new_form
        context['custom']=Bookings.objects.filter(date__gte=datetime.date.today())
    return render(request, 'register/dashboard.html', context)

Web-Cab-Sharing/cabsharing/register/templates/register/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="{% url 'register:user_dashboard'%}"> Web Cabs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bookings:bookings_create' %}">
            <span class="fas fa-map-marker" aria-hidden="true"></span>
            New Booking
            <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">My Bookings</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="#">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Help</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'register:user_logout' %}">Logout</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

Web-Cab-Sharing/cabsharing/register/templates/register/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Register{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/>


</head>
<body>
<!--Navbar-->
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'user_login' %}">Web Cabs</a>
        </div>
    </div>
</nav>
<!--/.Navbar-->
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

Web-Cab-Sharing/cabsharing/register/templates/register/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Register{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="{% url 'register:user_dashboard'%}"> Web Cabs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bookings:bookings_create' %}">
            <span class="fas fa-map-marker" aria-hidden="true"></span>
            New Booking
            <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bookings:my_bookings' %}">My Bookings</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'accounts:user_detail' pk=user.pk %}">Profile</a>
          <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Help</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'register:user_logout' %}">Logout</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


<div class="container-fluid">
  <div class="row">
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>
    </main>
  </div>
</div>
<div class="container-fluid" style="padding-bottom: 30px">
    <div class="row">
    <div class="col-lg-3  ">
    <div class="container">
      <div class="container text-white" style="background-color:#00796b">
        <!-- {% if hehehe.count == 0 %}
        {% else %}
        <div class="text-center">
          Now showing
        </div>
        {% endif %} -->

        {% for he in hehehe %}
        <p class='mt-1' style='padding:0; margin:0;'>{{he}}</p>
        {% endfor %}
      </div>
      <div class="card mt-3">
        <div class="card-body">
          <div class="container">
            <form method="post">
              {% csrf_token %}
              {{ form|crispy }}
              {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
              {% endfor %}
              <div class="text-center">
                <button type="submit" class="btn btn-success ">Filter</button>
              </div>
            </form>
            <hr>
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="col-lg-9">
    <div class="container">
      <div class="row">
        <div class="card-group ">
          <!-- <div class="col-md-4"> -->
          {% if custom.count == 0 %}
          <div class="container">
            <h1 class='mt-5' style="text-align:center; color:#00796b;" id="no_booking">No Bookings</h1>
          </div>
          {% endif %}
          {% for booking in custom %}
          <div class="col-lg-6">
            <!-- {% if user.is_member %}
              sjfhskjhf
              {% endif %}
              {% if request.user in booking.members.all %}
              hahahahahah
              {% endif %} -->
            {% if user.username == booking.creator %}
            <div class="card text-white border-secondary mx-auto mt-3 mb-4 " style="background-color:rgb(23, 38, 87); border-radius=5px;">
              {% else %}
              <div class="card text-white border-secondary mx-auto mt-3 mb-4 " style="background-color:rgb(23, 38, 87); border-radius=5px;">
                {% endif %}

                <div class="card-body" style='border: 1px solid rgb(23, 38, 87) '>
                    <div class="card-title text-center">

                    </div>
                  <div class="card-text">
                    <h6>From : {{booking.start_position}}</h6>
                    <h6>To : {{booking.destination}}</h6>
                    <h6>Date : {{booking.date|date:'d-m-Y'}}</h6>
                    <h6>Time : {{booking.time}}</h6>
                    <h6>Group-Admin : {{booking.creator}}</h6>
                    <h6>No. of Members : {{booking.members.count|add:"1"}}<small style='text-muted'> /{{booking.max_members}}</small></h6>
                    <br>
                      <div class="card-link">
                      {% if user.username == booking.creator %}
                      <a href="{% url 'bookings:bookings_update' pk=booking.pk %}" class='btn btn-warning btn-sm '>Edit</a>
                      <a href="{% url 'bookings:bookings_delete' pk=booking.pk %}" class='btn btn-danger btn-sm '>Delete</a>
                      {% else %}
                          {% if booking.members.count|add:"1" < booking.max_members %}
                              <a href="{% url 'bookings:group_join' pk=booking.pk %}" class="btn btn-success btn-sm">Join</a>
                          {% else %}
                              <a href="{% url 'bookings:group_join' pk=booking.pk %}" class="btn btn-success btn-sm disabled">Join</a>
                          {% endif %}
                          <a href="{% url 'bookings:group_leave' pk=booking.pk %}" class='btn btn-info btn-sm'>Leave</a>
                      {% endif %}

                      <a href="{% url 'bookings:group_info' pk=booking.pk %}" class='btn btn-secondary btn-sm'>Info</a>
                              </div>
                  </div>
                </div>

              </div>
            </div>
            {% endfor %}
            <br>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
</div>

















<!--
{% if object_list %}
<h1> Here are all the bookings</h1>
    {% for bookings in object_list %}
        <ul>
          <li>{{bookings.destinations}}</li>
        </ul>
    {% endfor %}
{% else %}
    <h3>There are no bookings.</h3>
{% endif %}
-->
<!--
      <div class="container-fluid mt-5" style='background-color:  rgb(28, 26, 27); position: fixed; bottom: 1px; padding: 10px;>
        <div class="row">
          <div class="col-md-3" style='border-right:1px solid rgb(62, 63, 64)'>
            <h5 style='color:rgb(176, 172, 175);'>IIT Guwahati</h5>
            <a href="http://www.iitg.ac.in/" style="color:rgb(227, 228, 230)">IIT Guwahati</a>
            <br>
          </div>
          <div class="col-md-6" style="border-right:1px solid rgb(62, 63, 64)">
            <h5 class='text-center' style='color:rgb(176, 172, 175); align:center;'>Contact Us</h5>
            <div class="row">
              <div class="col-6 " style="color:rgb(227, 228, 230)">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p>
              </div>
              <div class="col-6 " style="color:rgb(227, 228, 230)">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p>

              </div>
            </div>
            <br>
          </div>
          <div class="col-md-3" style='align:right;'>
            <h5 style='color:rgb(176, 172, 175)'>Follow Us</h5>
            <a href="https://www.iitg.ac.in/stud/gymkhana/technical/home/CodingHome.html" style="color:rgb(227, 228, 230)">Coding Club</a><br>
            <a href="https://www.facebook.com/codingclubiitg/" style="color:rgb(227, 228, 230)">facebook</a>
          </div>
        </div>

      </div>

-->
<!-- Footer -->
<footer class="page-footer font-small blue pt-4" style="background: #212529 ; color: white; padding: 30px;">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-2 mt-md-0 mt-3">

        <!-- Content -->
        <h5 style='color:rgb(176, 172, 175);'>IIT Guwahati</h5>
        <a href="http://www.iitg.ac.in/" style="color:rgb(227, 228, 230)">IIT Guwahati</a>
        <br>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">
      <div class="col-md-1 mt-md-0 mt-3"></div>
      <!-- Grid column -->
      <div class="col-md-5 mt-md-0 mt-3">

        <h5 class='text-center' style='color:rgb(176, 172, 175); align:center;'>Contact Us</h5>
            <div class="row">
              <div class="col-6 " style="color:rgb(227, 228, 230)">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p>
              </div>
              <div class="col-6 " style="color:rgb(227, 228, 230)">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p>

              </div>
            </div>
            <br>
      </div>

      <div class="col-md-1 mt-md-0 mt-3"></div>
        <!-- Links
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>-->
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Contact Us</h5>

        <ul class="list-unstyled">
          <li>
            <a href="https://www.iitg.ac.in/stud/gymkhana/technical/home/CodingHome.html" style="color:rgb(227, 228, 230)">Coding Club</a>
          </li>
          <li>
            <a href="https://www.facebook.com/codingclubiitg/" style="color:rgb(227, 228, 230)">facebook</a
          </li>
          <li>
            <a href="https://www.instagram.com/codingclubiitg/" style="color:rgb(227, 228, 230)">Instagram</a>
          </li>
          <li>
            <a href="mailto:techsec@iitg.ac.in" style="color:rgb(227, 228, 230)">Mail</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <!-- Copyright -->

</footer>
<!-- Footer -->
<!-- Footer -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>