Web-Cab-Sharing/cabsharing/accounts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='user_login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html') , name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',email_template_name='accounts/password_reset_email.html',subject_template_name='accounts/password_reset_subject.txt'),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    # normal urls are not working in my case

    re_path(r'^(?P<pk>\d+)/detail/$', views.UserDetailView.as_view(), name='user_detail'),
    # re_path(r'^(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(template_name='accounts/user_delete.html'), name='user_delete'),

    re_path(r'^(?P<pk>\d+)/update/$', views.UserUpdateView.as_view(template_name='accounts/haha.html'), name='user_update'),


    ]

Web-Cab-Sharing/cabsharing/cabsharing/urls.py
from django.contrib import admin
from django.urls import path, include
#from register.views import homepage
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', auth_views.LoginView.as_view(template_name='register/homepage.html'), name='user_login'),
    path('bookings/', include('bookings.urls')),
    #path('password_reset', auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html', name = 'password_reset')),
]







#path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='user_login'),

Web-Cab-Sharing/cabsharing/register/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'register'


urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.filter, name='user_dashboard'),
    path('logout/', auth_views.LogoutView.as_view(), name='user_logout'),
]

Web-Cab-Sharing/cabsharing/accounts/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
HOSTELS=[
        ('Brahmaputra', 'Brahmaputra'),
        ('Dihing', 'Dihing'),
        ('Manas', 'Manas'),
        ('Lohit', 'Lohit'),
        ('Dhansiri', 'Dhansiri'),
        ('Kapili', 'Kapili'),
        ('Siang', 'Siang'),
        ('Kameng', 'Kameng'),
        ('Umiam', 'Umiam'),
        ('Barak', 'Barak'),
        ('Subhansiri', 'Subhansiri'),
        ('Disang/Dibang', 'Disang/Dibang'),
]

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hostel = models.CharField(blank=False, max_length=50 ,choices=HOSTELS)
    profile_pic = models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')
    # add any gender-neutral photo in default

    def __str__(self):
        return self.user.username

    # def get_absolute_url(self):
    #     return reverse('accounts:user_detail' , kwargs={'pk':self.pk})

Web-Cab-Sharing/cabsharing/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

HOSTELS=[
        ('Brahmaputra', 'Brahmaputra'),
        ('Dihing', 'Dihing'),
        ('Manas', 'Manas'),
        ('Lohit', 'Lohit'),
        ('Dhansiri', 'Dhansiri'),
        ('Kapili', 'Kapili'),
        ('Siang', 'Siang'),
        ('Kameng', 'Kameng'),
        ('Umiam', 'Umiam'),
        ('Barak', 'Barak'),
        ('Subhansiri', 'Subhansiri'),
        ('Disang/Dibang', 'Disang/Dibang'),
]


def emailcheck(value):
    if(value[-11::]!='@iitg.ac.in'):
        raise forms.ValidationError("You must use email-id provided by IIT-Guwahati.")

class UserForm(forms.ModelForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    email=forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Email'}), validators=[emailcheck])
    class Meta():
        model=User
        fields=('username','email','password')

# def clean_email(self):
#     email=self.cleaned_data['email']
#     if(email(11,))

class UserProfileForm(forms.ModelForm):

    hostel=forms.ChoiceField(required=True, choices=HOSTELS)

    class Meta():
        model=UserProfile
        fields=('hostel', 'profile_pic')

Web-Cab-Sharing/cabsharing/accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import login, authenticate
from .forms import UserProfileForm, UserForm
from django.views.generic import DetailView, DeleteView, UpdateView
from django.contrib.auth.models import User
from accounts.models import UserProfile
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/user_detail.html'

# class UserDeleteView(LoginRequiredMixin, DeleteView):
#     model=User
#     success_url=reverse_lazy('index')


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    fields = ['profile_pic']
    template_name = 'accounts/haha.html'
    success_url = reverse_lazy('register:user_dashboard')
    # need to change it to detail
    extra_context = {'userprofile': UserProfileForm()}

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.User.pk})


class UserProfileUpateView(LoginRequiredMixin, UpdateView):
    model=UserProfile
    fields=['profile_pic']

Web-Cab-Sharing/cabsharing/accounts/templates/accounts/haha.html
{% extends 'register/base.html' %}
{% load crispy_forms_tags %}

{% block title%}
Update
{% endblock %}

{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'register:user_dashboard' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Update</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-warning btn-lg">Save</button>
          </div>
          <br>

        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Web-Cab-Sharing/cabsharing/accounts/templates/accounts/login.html
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'index' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Login</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg">Login</button>
          </div>
          <br>
          <hr>
          <a href="{% url 'accounts:password_reset' %}">forgot password?</a>
          <p class='text-center'>Don't have an account yet? <a href="{% url 'accounts:user_signup' %}">SignUp</a></p>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Web-Cab-Sharing/cabsharing/accounts/templates/accounts/password_change_done.html
{% extends 'register/base.html' %}

{% block title %}
Congratulations
{% endblock %}

{% block content %}
<div class="container" style='width:30rem background-color:rgb() ;'>
  <h3>Your Password has been successfully changed.</h3>
  <h6><a href="{% url 'user_login' %}">Click</a> here to go to the site again.</h6>
</div>
{% endblock %}

Web-Cab-Sharing/cabsharing/accounts/templates/accounts/password_change_form.html
{% extends 'register/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Change Password
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'register:user_dashboard' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Password Change</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-primary btn-lg">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Web-Cab-Sharing/cabsharing/accounts/templates/accounts/user_detail.html
{% extends 'register/base.html' %}


{% block title %}
Profile
{% endblock %}


{% block content %}
<br><br><br><br>
<div class="container">
  <div class="card mx-auto" style='width: 30rem;'>
    <img class='card-img-top' src="{{user.userprofile.profile_pic.url}}" alt="none">
    <div class="card-img-overlay">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'register:user_dashboard' %}"><span style="text-color:white;" aria-hidden="true">×</span></a></button>

    </div>
    <div class="card-body">
      <div class="card-title text-center">
        <h2>{{user.username}}</h2>
      </div>
      <div class="card-text">
        <h6>Email: {{user.email}}</h6>
          <br>
        </div>


    </div>
  </div>
  <br>
  <div class="text-center">
      <a href="{% url 'accounts:user_update' pk=user.pk %}" class=' btn btn-info'>Update profile</a>
    <a href="{% url 'accounts:user_update' pk=user.pk %}" class=' btn btn-info'>Update profile_pic</a>
  </div>

</div>
{% endblock %}